# Funding options for the project
# Uncomment and add your sponsorship links if applicable

# github: [username]
# patreon: username
# ko_fi: username
# custom: ["https://example.com/donate", "https://example.com/sponsor"]
